// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EmployeeResponse struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Age       int    `json:"age"`
	Position  string `json:"position"`
	ViewCount int    `json:"viewCount"`
}

type NewEmployee struct {
	Name     string `json:"name"`
	Age      int    `json:"age"`
	Position string `json:"position"`
}

type UpdateEmployee struct {
	Name     string `json:"name"`
	Position string `json:"position"`
}
